export default {
    countries: [
        {value: 'Afghanistan', countryCode: 'af'},
        {value: 'Aland Islands', countryCode: 'ax'},
        {value: 'Albania', countryCode: 'al'},
        {value: 'Algeria', countryCode: 'dz'},
        {value: 'American Samoa', countryCode: 'as'},
        {value: 'Andorra', countryCode: 'ad'},
        {value: 'Angola', countryCode: 'ao'},
        {value: 'Anguilla', countryCode: 'ai'},
        {value: 'Antigua', countryCode: 'ag'},
        {value: 'Argentina', countryCode: 'ar'},
        {value: 'Armenia', countryCode: 'am'},
        {value: 'Aruba', countryCode: 'aw'},
        {value: 'Australia', countryCode: 'au'},
        {value: 'Austria', countryCode: 'at'},
        {value: 'Azerbaijan', countryCode: 'az'},
        {value: 'Bahamas', countryCode: 'bs'},
        {value: 'Bahrain', countryCode: 'bh'},
        {value: 'Bangladesh', countryCode: 'bd'},
        {value: 'Barbados', countryCode: 'bb'},
        {value: 'Belarus', countryCode: 'by'},
        {value: 'Belgium', countryCode: 'be'},
        {value: 'Belize', countryCode: 'bz'},
        {value: 'Benin', countryCode: 'bj'},
        {value: 'Bermuda', countryCode: 'bm'},
        {value: 'Bhutan', countryCode: 'bt'},
        {value: 'Bolivia', countryCode: 'bo'},
        {value: 'Bosnia', countryCode: 'ba'},
        {value: 'Botswana', countryCode: 'bw'},
        {value: 'Bouvet Island', countryCode: 'bv'},
        {value: 'Brazil', countryCode: 'br'},
        {value: 'British Virgin Islands', countryCode: 'vg'},
        {value: 'Brunei', countryCode: 'bn'},
        {value: 'Bulgaria', countryCode: 'bg'},
        {value: 'Burkina Faso', countryCode: 'bf'},
        {value: 'Burma', countryCode: 'mm', alias: 'Myanmar'},
        {value: 'Burundi', countryCode: 'bi'},
        {value: 'Caicos Islands', countryCode: 'tc'},
        {value: 'Cambodia', countryCode: 'kh'},
        {value: 'Cameroon', countryCode: 'cm'},
        {value: 'Canada', countryCode: 'ca'},
        {value: 'Cape Verde', countryCode: 'cv'},
        {value: 'Cayman Islands', countryCode: 'ky'},
        {value: 'Central African Republic', countryCode: 'cf'},
        {value: 'Chad', countryCode: 'td'},
        {value: 'Chile', countryCode: 'cl'},
        {value: 'China', countryCode: 'cn'},
        {value: 'Christmas Island', countryCode: 'cx'},
        {value: 'Cocos Islands', countryCode: 'cc'},
        {value: 'Colombia', countryCode: 'co'},
        {value: 'Comoros', countryCode: 'km'},
        {value: 'Congo', countryCode: 'cd'},
        {value: 'Congo Brazzaville', countryCode: 'cg'},
        {value: 'Cook Islands', countryCode: 'ck'},
        {value: 'Costa Rica', countryCode: 'cr'},
        {value: 'Cote Divoire', countryCode: 'ci'},
        {value: 'Croatia', countryCode: 'hr'},
        {value: 'Cuba', countryCode: 'cu'},
        {value: 'Cyprus', countryCode: 'cy'},
        {value: 'Czech Republic', countryCode: 'cz'},
        {value: 'Denmark', countryCode: 'dk'},
        {value: 'Djibouti', countryCode: 'dj'},
        {value: 'Dominica', countryCode: 'dm'},
        {value: 'Dominican Republic', countryCode: 'do'},
        {value: 'Ecuador', countryCode: 'ec'},
        {value: 'Egypt', countryCode: 'eg'},
        {value: 'El Salvador', countryCode: 'sv'},
        {value: 'Equatorial Guinea', countryCode: 'gq'},
        {value: 'Eritrea', countryCode: 'er'},
        {value: 'Estonia', countryCode: 'ee'},
        {value: 'Ethiopia', countryCode: 'et'},
        {value: 'Europeanunion', countryCode: 'eu'},
        {value: 'Falkland Islands', countryCode: 'fk'},
        {value: 'Faroe Islands', countryCode: 'fo'},
        {value: 'Fiji', countryCode: 'fj'},
        {value: 'Finland', countryCode: 'fi'},
        {value: 'France', countryCode: 'fr'},
        {value: 'French Guiana', countryCode: 'gf'},
        {value: 'French Polynesia', countryCode: 'pf'},
        {value: 'French Territories', countryCode: 'tf'},
        {value: 'Gabon', countryCode: 'ga'},
        {value: 'Gambia', countryCode: 'gm'},
        {value: 'Georgia', countryCode: 'ge'},
        {value: 'Germany', countryCode: 'de'},
        {value: 'Ghana', countryCode: 'gh'},
        {value: 'Gibraltar', countryCode: 'gi'},
        {value: 'Greece', countryCode: 'gr'},
        {value: 'Greenland', countryCode: 'gl'},
        {value: 'Grenada', countryCode: 'gd'},
        {value: 'Guadeloupe', countryCode: 'gp'},
        {value: 'Guam', countryCode: 'gu'},
        {value: 'Guatemala', countryCode: 'gt'},
        {value: 'Guinea', countryCode: 'gn'},
        {value: 'Guinea-Bissau', countryCode: 'gw'},
        {value: 'Guyana', countryCode: 'gy'},
        {value: 'Haiti', countryCode: 'ht'},
        {value: 'Heard Island', countryCode: 'hm'},
        {value: 'Honduras', countryCode: 'hn'},
        {value: 'Hong Kong', countryCode: 'hk'},
        {value: 'Hungary', countryCode: 'hu'},
        {value: 'Iceland', countryCode: 'is'},
        {value: 'India', countryCode: 'in'},
        {value: 'Indian Ocean Territory', countryCode: 'io'},
        {value: 'Indonesia', countryCode: 'id'},
        {value: 'Iran', countryCode: 'ir'},
        {value: 'Iraq', countryCode: 'iq'},
        {value: 'Ireland', countryCode: 'ie'},
        {value: 'Israel', countryCode: 'il'},
        {value: 'Italy', countryCode: 'it'},
        {value: 'Jamaica', countryCode: 'jm'},
        {value: 'Jan Mayen', countryCode: 'sj', alias: 'Svalbard'},
        {value: 'Japan', countryCode: 'jp'},
        {value: 'Jordan', countryCode: 'jo'},
        {value: 'Kazakhstan', countryCode: 'kz'},
        {value: 'Kenya', countryCode: 'ke'},
        {value: 'Kiribati', countryCode: 'ki'},
        {value: 'Kuwait', countryCode: 'kw'},
        {value: 'Kyrgyzstan', countryCode: 'kg'},
        {value: 'Laos', countryCode: 'la'},
        {value: 'Latvia', countryCode: 'lv'},
        {value: 'Lebanon', countryCode: 'lb'},
        {value: 'Lesotho', countryCode: 'ls'},
        {value: 'Liberia', countryCode: 'lr'},
        {value: 'Libya', countryCode: 'ly'},
        {value: 'Liechtenstein', countryCode: 'li'},
        {value: 'Lithuania', countryCode: 'lt'},
        {value: 'Luxembourg', countryCode: 'lu'},
        {value: 'Macau', countryCode: 'mo'},
        {value: 'Macedonia', countryCode: 'mk'},
        {value: 'Madagascar', countryCode: 'mg'},
        {value: 'Malawi', countryCode: 'mw'},
        {value: 'Malaysia', countryCode: 'my'},
        {value: 'Maldives', countryCode: 'mv'},
        {value: 'Mali', countryCode: 'ml'},
        {value: 'Malta', countryCode: 'mt'},
        {value: 'Marshall Islands', countryCode: 'mh'},
        {value: 'Martinique', countryCode: 'mq'},
        {value: 'Mauritania', countryCode: 'mr'},
        {value: 'Mauritius', countryCode: 'mu'},
        {value: 'Mayotte', countryCode: 'yt'},
        {value: 'Mexico', countryCode: 'mx'},
        {value: 'Micronesia', countryCode: 'fm'},
        {value: 'Moldova', countryCode: 'md'},
        {value: 'Monaco', countryCode: 'mc'},
        {value: 'Mongolia', countryCode: 'mn'},
        {value: 'Montenegro', countryCode: 'me'},
        {value: 'Montserrat', countryCode: 'ms'},
        {value: 'Morocco', countryCode: 'ma'},
        {value: 'Mozambique', countryCode: 'mz'},
        {value: 'Namibia', countryCode: 'na'},
        {value: 'Nauru', countryCode: 'nr'},
        {value: 'Nepal', countryCode: 'np'},
        {value: 'Netherlands', countryCode: 'nl'},
        {value: 'Netherlandsantilles', countryCode: 'an'},
        {value: 'New Caledonia', countryCode: 'nc'},
        {value: 'New Guinea', countryCode: 'pg'},
        {value: 'New Zealand', countryCode: 'nz'},
        {value: 'Nicaragua', countryCode: 'ni'},
        {value: 'Niger', countryCode: 'ne'},
        {value: 'Nigeria', countryCode: 'ng'},
        {value: 'Niue', countryCode: 'nu'},
        {value: 'Norfolk Island', countryCode: 'nf'},
        {value: 'North Korea', countryCode: 'kp'},
        {value: 'Northern Mariana Islands', countryCode: 'mp'},
        {value: 'Norway', countryCode: 'no'},
        {value: 'Oman', countryCode: 'om'},
        {value: 'Pakistan', countryCode: 'pk'},
        {value: 'Palau', countryCode: 'pw'},
        {value: 'Palestine', countryCode: 'ps'},
        {value: 'Panama', countryCode: 'pa'},
        {value: 'Paraguay', countryCode: 'py'},
        {value: 'Peru', countryCode: 'pe'},
        {value: 'Philippines', countryCode: 'ph'},
        {value: 'Pitcairn Islands', countryCode: 'pn'},
        {value: 'Poland', countryCode: 'pl'},
        {value: 'Portugal', countryCode: 'pt'},
        {value: 'Puerto Rico', countryCode: 'pr'},
        {value: 'Qatar', countryCode: 'qa'},
        {value: 'Reunion', countryCode: 're'},
        {value: 'Romania', countryCode: 'ro'},
        {value: 'Russia', countryCode: 'ru'},
        {value: 'Rwanda', countryCode: 'rw'},
        {value: 'Saint Helena', countryCode: 'sh'},
        {value: 'Saint Kitts and Nevis', countryCode: 'kn'},
        {value: 'Saint Lucia', countryCode: 'lc'},
        {value: 'Saint Pierre', countryCode: 'pm'},
        {value: 'Saint Vincent', countryCode: 'vc'},
        {value: 'Samoa', countryCode: 'ws'},
        {value: 'San Marino', countryCode: 'sm'},
        {value: 'Sandwich Islands', countryCode: 'gs'},
        {value: 'Sao Tome', countryCode: 'st'},
        {value: 'Saudi Arabia', countryCode: 'sa'},
        {value: 'Scotland', countryCode: 'gb sct'},
        {value: 'Senegal', countryCode: 'sn'},
        {value: 'Serbia', countryCode: 'cs'},
        {value: 'Serbia', countryCode: 'rs'},
        {value: 'Seychelles', countryCode: 'sc'},
        {value: 'Sierra Leone', countryCode: 'sl'},
        {value: 'Singapore', countryCode: 'sg'},
        {value: 'Slovakia', countryCode: 'sk'},
        {value: 'Slovenia', countryCode: 'si'},
        {value: 'Solomon Islands', countryCode: 'sb'},
        {value: 'Somalia', countryCode: 'so'},
        {value: 'South Africa', countryCode: 'za'},
        {value: 'South Korea', countryCode: 'kr'},
        {value: 'Spain', countryCode: 'es'},
        {value: 'Sri Lanka', countryCode: 'lk'},
        {value: 'Sudan', countryCode: 'sd'},
        {value: 'Suriname', countryCode: 'sr'},
        {value: 'Swaziland', countryCode: 'sz'},
        {value: 'Sweden', countryCode: 'se'},
        {value: 'Switzerland', countryCode: 'ch'},
        {value: 'Syria', countryCode: 'sy'},
        {value: 'Taiwan', countryCode: 'tw'},
        {value: 'Tajikistan', countryCode: 'tj'},
        {value: 'Tanzania', countryCode: 'tz'},
        {value: 'Thailand', countryCode: 'th'},
        {value: 'Timorleste', countryCode: 'tl'},
        {value: 'Togo', countryCode: 'tg'},
        {value: 'Tokelau', countryCode: 'tk'},
        {value: 'Tonga', countryCode: 'to'},
        {value: 'Trinidad', countryCode: 'tt'},
        {value: 'Tunisia', countryCode: 'tn'},
        {value: 'Turkey', countryCode: 'tr'},
        {value: 'Turkmenistan', countryCode: 'tm'},
        {value: 'Tuvalu', countryCode: 'tv'},
        {value: 'U.A.E.', countryCode: 'ae', alias: 'United Arab Emirates'},
        {value: 'Uganda', countryCode: 'ug'},
        {value: 'Ukraine', countryCode: 'ua'},
        {value: 'United Kingdom', countryCode: 'gb', alias: 'uk'},
        {value: 'United States', countryCode: 'us', alias: 'America'},
        {value: 'Uruguay', countryCode: 'uy'},
        {value: 'US Minor Islands', countryCode: 'um'},
        {value: 'US Virgin Islands', countryCode: 'vi'},
        {value: 'Uzbekistan', countryCode: 'uz'},
        {value: 'Vanuatu', countryCode: 'vu'},
        {value: 'Vatican City', countryCode: 'va'},
        {value: 'Venezuela', countryCode: 've'},
        {value: 'Vietnam', countryCode: 'vn'},
        {value: 'Wales', countryCode: 'gb wls'},
        {value: 'Wallis and Futuna', countryCode: 'wf'},
        {value: 'Western Sahara', countryCode: 'eh'},
        {value: 'Yemen', countryCode: 'ye'},
        {value: 'Zambia', countryCode: 'zm'},
        {value: 'Zimbabwe', countryCode: 'zw'}
    ],
    age: [
        {value: '18'},
        {value: '19'},
        {value: '20'},
        {value: '21'},
        {value: '22'},
        {value: '23'},
        {value: '24'},
        {value: '25'},
        {value: '26'},
        {value: '27'},
        {value: '28'},
        {value: '29'},
        {value: '30'},
        {value: '31'},
        {value: '32'},
        {value: '33'},
        {value: '34'},
        {value: '35'},
        {value: '36'},
        {value: '37'},
        {value: '38'},
        {value: '39'},
        {value: '40'},
        {value: '41'},
        {value: '42'},
        {value: '43'},
        {value: '44'},
        {value: '45'},
        {value: '46'},
        {value: '47'},
        {value: '48'},
        {value: '49'},
        {value: '50'},
        {value: '51'},
        {value: '52'},
        {value: '53'},
        {value: '54'},
        {value: '55'},
        {value: '56'},
        {value: '57'},
        {value: '58'},
        {value: '59'},
        {value: '60'},
        {value: '61'},
        {value: '62'},
        {value: '63'},
        {value: '64'},
        {value: '65'},
        {value: '66'},
        {value: '67'},
        {value: '68'},
        {value: '69'},
        {value: '70'},
        {value: '71'},
        {value: '72'},
        {value: '73'},
        {value: '74'},
        {value: '75'},
        {value: '76'},
        {value: '77'},
        {value: '78'},
        {value: '79'},
        {value: '80'},
        {value: '81'},
        {value: '82'},
        {value: '83'},
        {value: '84'},
        {value: '85'},
        {value: '86'},
        {value: '87'},
        {value: '88'},
        {value: '89'},
        {value: '90'},
        {value: '91'},
        {value: '92'},
        {value: '93'},
        {value: '94'},
        {value: '95'},
        {value: '96'},
        {value: '97'},
        {value: '98'},
        {value: '99'},
    ],
    validateEmail: function(email)
    {
        let re = /^(([^<>()[\]\\.,;:\s@]+(\.[^<>()[\]\\.,;:\s@]+)*)|(.+))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(email);
    },
    validatePassword: function(password) {
        let re = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/;
        return re.test(password);
    },
    validateUsername: function(username) {
        let re = /^[A-Za-z0-9]+(?:[ _-][A-Za-z0-9]+)*$/;
        return re.test(username)
    },
    validateFirstName: function(name) {
        let re = /^(?=.{1,20}$)[a-z]+(?:['_.\s][a-z]+)*$/i;
        return re.test(name);
    },
    sleepLoader: function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    },
    checkWarnings: function(data) {
        let warnings = false;
        Object.entries(data).forEach(([key, value]) => {
            if (value.length > 0)
                warnings = true;
        });
        return warnings;
    }
}